import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ZeraClientProviders } from "@/components/Zera/ZeraClientProviders";

const inter = Inter({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} antialiased dark`}>
                <ZeraClientProviders>{children}</ZeraClientProviders>
            </body>
        </html>
    );
}
